### ISSUE TITLE
Error message should be written on STDERR instead of STDIN

### ISSUE THREAD

**Issue by 4slan** [4slan/42sh#1]
Error message should be written on `STDERR_FILENO (2)` instead of `STDERR_FILENO (1)`

https://github.com/4slan/42sh/blob/af04a82ea892c6b20228f302cc5e3038cf6939f3/lib/ft/src/print/ft_printerr.c#L21

**Comment by abaisago** [comment]
e265574b16ee1fee7bac77bde9f6524ae9490098 fixes the issue
